apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: wordpress
  name: mysql-pv
  labels:
    type: local
    app: mysql
    tier: database
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mysql-data"