apiVersion: v1
kind: Secret
metadata:
  namespace: wordpress
  name: mysql-secret
  labels:
    app: mysql
    tier: database
type: Opaque
data:
  password: cGFzc3dvcmQ= 
  user: YWRtaW4=
  database: d29yZHByZXNz